-- WebLoom Supabase schema
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  role text not null default 'user' check (role in ('user','owner')),
  plan text not null default 'free' check (plan in ('free','pro')),
  free_capture_used boolean not null default false,
  stripe_customer_id text unique,
  stripe_subscription_id text unique,
  subscription_status text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  source_url text not null,
  hostname text,
  status text not null default 'queued' check (status in ('queued','running','done','error')),
  engine text not null default 'webloom',
  file_count integer not null default 0,
  byte_count bigint not null default 0,
  failed_count integer not null default 0,
  preview_path text,
  archive_path text,
  error text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  finished_at timestamptz
);

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  project_id uuid references public.projects(id) on delete set null,
  kind text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists projects_user_created_idx on public.projects(user_id, created_at desc);
create index if not exists usage_user_created_idx on public.usage_events(user_id, created_at desc);

alter table public.profiles enable row level security;
alter table public.projects enable row level security;
alter table public.usage_events enable row level security;

drop policy if exists "profiles own row" on public.profiles;
create policy "profiles own row" on public.profiles for select using (auth.uid() = id);

drop policy if exists "projects own rows" on public.projects;
create policy "projects own rows" on public.projects for select using (auth.uid() = user_id);

drop policy if exists "usage own rows" on public.usage_events;
create policy "usage own rows" on public.usage_events for select using (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Atomic entitlement check + one-free-capture consumption.
create or replace function public.consume_capture_entitlement(p_user uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  p public.profiles%rowtype;
begin
  select * into p from public.profiles where id = p_user for update;
  if not found then
    raise exception 'profile_not_found';
  end if;

  if p.role = 'owner' then
    return jsonb_build_object('allowed', true, 'reason', 'owner', 'plan', 'owner');
  end if;

  if p.plan = 'pro' and coalesce(p.subscription_status,'') in ('active','trialing') then
    return jsonb_build_object('allowed', true, 'reason', 'pro', 'plan', 'pro');
  end if;

  if not p.free_capture_used then
    update public.profiles
      set free_capture_used = true, updated_at = now()
      where id = p_user;
    return jsonb_build_object('allowed', true, 'reason', 'free', 'plan', 'free');
  end if;

  return jsonb_build_object('allowed', false, 'reason', 'upgrade_required', 'plan', 'free');
end;
$$;

revoke all on function public.consume_capture_entitlement(uuid) from public;
grant execute on function public.consume_capture_entitlement(uuid) to service_role;

-- Webhook helper: subscription state is server-authoritative.
create or replace function public.set_subscription_state(
  p_user uuid,
  p_customer text,
  p_subscription text,
  p_status text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.profiles
  set stripe_customer_id = coalesce(p_customer, stripe_customer_id),
      stripe_subscription_id = coalesce(p_subscription, stripe_subscription_id),
      subscription_status = p_status,
      plan = case when p_status in ('active','trialing') then 'pro' else 'free' end,
      updated_at = now()
  where id = p_user;
end;
$$;

revoke all on function public.set_subscription_state(uuid,text,text,text) from public;
grant execute on function public.set_subscription_state(uuid,text,text,text) to service_role;
